"""Dynamic Systems and Control Simulation Engine (Simulink-like block diagram & ODE solver)."""

from .blocks import (
    Block,
    # Continuous & State-Space
    IntegratorBlock,
    DerivativeBlock,
    TransferFunctionBlock,
    StateSpaceBlock,
    TransportDelayBlock,
    # Nonlinear & Physical
    SaturationBlock,
    RateLimiterBlock,
    DeadZoneBlock,
    BacklashBlock,
    RelayBlock,
    CoulombViscousFrictionBlock,
    QuantizerBlock,
    # Math & Operations
    GainBlock,
    SumBlock,
    ProductBlock,
    MathFunctionBlock,
    LookupTable1DBlock,
    SwitchBlock,
    # Discrete Control
    ZeroOrderHoldBlock,
    UnitDelayBlock,
    PIDBlock,
    # Sources & Sinks
    ConstantBlock,
    StepSourceBlock,
    RampSourceBlock,
    SineSourceBlock,
    PulseGeneratorBlock,
    BandLimitedWhiteNoiseBlock,
    ScopeSinkBlock,
)
from .scheduler import SystemDiagram, Scheduler
from .ode_solver import DynamicSystemSimulator

__all__ = [
    "Block",
    "IntegratorBlock",
    "DerivativeBlock",
    "TransferFunctionBlock",
    "StateSpaceBlock",
    "TransportDelayBlock",
    "SaturationBlock",
    "RateLimiterBlock",
    "DeadZoneBlock",
    "BacklashBlock",
    "RelayBlock",
    "CoulombViscousFrictionBlock",
    "QuantizerBlock",
    "GainBlock",
    "SumBlock",
    "ProductBlock",
    "MathFunctionBlock",
    "LookupTable1DBlock",
    "SwitchBlock",
    "ZeroOrderHoldBlock",
    "UnitDelayBlock",
    "PIDBlock",
    "ConstantBlock",
    "StepSourceBlock",
    "RampSourceBlock",
    "SineSourceBlock",
    "PulseGeneratorBlock",
    "BandLimitedWhiteNoiseBlock",
    "ScopeSinkBlock",
    "SystemDiagram",
    "Scheduler",
    "DynamicSystemSimulator",
]
